CREATE TYPE "DocumentType_new" AS ENUM (
  'DRIVERS_LICENSE',
  'DRIVERS_LICENSE_BACK',
  'GDL',
  'VEHICLE_REGISTRATION',
  'ROAD_TAX',
  'PUSPAKOM',
  'APAD_PERMIT',
  'VEHICLE_PHOTO_FRONT',
  'VEHICLE_PHOTO_BACK',
  'VEHICLE_PHOTO_LEFT',
  'VEHICLE_PHOTO_RIGHT',
  'VEHICLE_PHOTO_INTERIOR',
  'BANK_STATEMENT',
  'POLICE_CLEARANCE',
  'INSURANCE',
  'PROFILE_PHOTO',
  'ID_PROOF',
  'MYKAD_FRONT',
  'MYKAD_BACK',
  'SELFIE',
  'PASSPORT',
  'WORK_PERMIT_PLKS'
);

ALTER TABLE "DriverDocument" ADD COLUMN "expiryDate" TEXT;

ALTER TABLE "DriverDocument" ALTER COLUMN "type" TYPE "DocumentType_new"
USING ("type"::text::"DocumentType_new");

DROP TYPE "DocumentType";
ALTER TYPE "DocumentType_new" RENAME TO "DocumentType";
